Support optional "teardown" script to run before kexec
zbm-dev/zfsbootmenu pull request #104
Opened 2020-12-07 07:21 UTC by ahesford

A new `zfsbootmenu_teardown` dracut option has been added to `module-init.sh` that, when set to a path that refers to an executable, will install the named executable as `/libexec/zfsbootmenu-teardown` in the initramfs. In `kexec_kernel`, if `/libexec/zfsbootmenu-teardown` is found to exist and be executable, the script will be run immediately before the final `kexec` call to jump into the new kernel.

On my 2015 "VoidBook Air", the system keyboard, trackpad and bluetooth controller are connected to the XHCI USB hub. These devices are fully functional in ZBM, but when I boot the final kernel,  I can see the hub but not the peripherals. With the following teardown hook:
```bash
#!/bin/sh

SYS_XHCI=/sys/bus/pci/drivers/xhci_hcd

for DEVPATH in ${SYS_XHCI}/????:??:??.?; do
	[ -L "${DEVPATH}" ] || continue
	DEVICE="${DEVPATH#${SYS_XHCI}/}"
	echo "Tearing down USB controller ${DEVICE}..."
	echo "${DEVICE}" > ${SYS_XHCI}/unbind
done
```
I can unbind the XHCI device from the driver, which allows the final kernel to properly initialize the device and my peripherals to function.

I suspect there are a few use cases like this where a teardown script will be useful to ease the kexec transition. The script is not intended to interact with any ZFS pools or filesystems, so is executed at the last possible moment (specifically, after the pool is exported.)

2020-12-07 16:36 UTC, ahesford commented
The XHCI teardown script has been added to `contrib/`.

2020-12-08 01:15 UTC, zdykstra requested changes
Very clean/user-expandable solution here. It might be nice to document this mechanism in `zfsbootmenu.7` under a new section, and to update the Makefile to copy these to /usr/share/examples/zfsbootmenu/contrib.

2020-12-08 05:53 UTC, ahesford commented
On 2020-12-07 at 20:15 (UTC -0500), Zach Dykstra wrote:
> @zdykstra requested changes on this pull request.
> 
> Very clean/user-expandable solution here. It might be nice to document
> this mechanism in `zfsbootmenu.7` under a new section, and to update
> the Makefile to copy these to /usr/share/examples/zfsbootmenu/contrib.

I incorporated your requests. Not seeing a need for another level in the
hierarchy, I left out the `contrib` subdirectory in the `examples` tree.
If you object, I will put it in the subdirectory.

2020-12-08 14:38 UTC, zdykstra approved these changes

2020-12-08 14:45 UTC, closed without merging