zfsbootmenu-core: remove SIGINT trap when spawning e-shell
zbm-dev/zfsbootmenu pull request #487
Opened 2023-09-18 18:52 UTC by midzelis

After emergency_shell() is called, no commands can be interrupted (ctrl-c). 

reproduce:
1) go to e-shell
2) execute `sleep 5`
3) press ctrl-c
4) sleep is not interrupted

fix
untrap SIGINT before launching e-shell

2023-09-18 19:25 UTC, zdykstra commented
The trap needs to be restored after `/bin/bash` exits

2023-09-18 19:30 UTC, zdykstra requested changes
The trap needs to be restored after /bin/bash exits

2023-09-18 19:31 UTC, ahesford commented
It's probably best to just
```sh
( trap - SIGINT; exec /bin/bash -i )
```
to avoid having to restore it. (Assuming this works as expected.)

2023-09-19 01:31 UTC, ahesford approved these changes
The general concept works in a simple test script, but I haven't undertaken any tests in ZFSBootMenu itself.

2023-09-20 00:16 UTC, zdykstra requested changes
As near as I can tell this is working as expected. Squash the commits and it's good to go.

2023-09-21 14:40 UTC, closed without merging